STM8_Lib: i2c.h File Reference
i2c.h File Reference
implementation of I2C functions/macros
#include <stdint.h>
#include "stm8as.h"
Macros
#define I2C_BUSY (I2C.SR3.reg.BUSY)
check I2C busy flag
Functions
void i2c_init (void)
configure I2C bus as master in standard mode
uint8_t i2c_start (void)
generate I2C start condition
uint8_t i2c_stop (void)
generate I2C stop condition
uint8_t i2c_send (uint8_t addr, uint8_t numTx, uint8_t *Tx)
write data via I2C
uint8_t i2c_request (uint8_t addr, uint8_t numRx, uint8_t *Rx)
request data via I2C as master
void i2c_ISR (void) __interrupt(__I2C_VECTOR__)
ISR for I2C bus (required for slave operation)
Detailed Description
implementation of I2C functions/macros
declaration of I2C functions/macros
Author
G. Icking-Konert
Date
2013-11-22
Version
0.1
implementation of functions for I2C bus communication For I2C bus, see http://en.wikipedia.org/wiki/I2C
Author
G. Icking-Konert
Date
2013-11-22
Version
0.1
declaration of functions for I2C bus communication For I2C bus, see http://en.wikipedia.org/wiki/I2C
Definition in file i2c.h.
Macro Definition Documentation
#define I2C_BUSY (I2C.SR3.reg.BUSY)
check I2C busy flag
Definition at line 29 of file i2c.h.
Referenced by lcd_print(), and set_dig_poti().
Function Documentation
void i2c_init (void)
configure I2C bus as master in standard mode
configure I2C bus as master in standard mode
configure I2C bus as master in standard mode, BR=100kHz, 7bit address, 250ns rise time
Definition at line 37 of file i2c.c.
References gpio_init(), OUTPUT_OPENDRAIN_FAST, PIN_1, and PIN_2.
                {
  // configure I2C pins PE1(=SCL) and PE2(=SDA)
  gpio_init(&PORT_E, PIN_1 | PIN_2, OUTPUT_OPENDRAIN_FAST);
  // init I2C bus
  I2C.CR1.byte          = 0x00;     // disable I2C, no clock stretching
  I2C.CR2.reg.ACK       = 1;        // enable ACK on address match
  I2C.FREQR.reg.FREQ    = 16;       // peripheral clock = 16MHz (f=val*1MHz)
  I2C.OARH.reg.ADDCONF  = 1;        // set 7b addressing mode
  I2C.OARL.reg.ADD      = 0x04;     // set own 7b addr to 0x04
  I2C.SR1.byte          = 0x00;     // clear status registers
  I2C.SR2.byte          = 0x00;
  I2C.SR3.byte          = 0x00;
  I2C.CCRL.reg.CCR      = 0x50;     // BR = 100kBaud (t_low = t_high = 80/16MHz)
  I2C.CCRH.byte         = 0x00;     // I2C standard mode
  I2C.TRISER.reg.TRISE  = 0x04;     // t_rise<250ns (<300ns for display driver)
  I2C.CR1.reg.PE        = 1;        // enable I2C module with broadcast receive disabled
} // i2c_init
void i2c_ISR (void)
ISR for I2C bus (required for slave operation)
Interrupt service routine for I2C bus (required for operation as slave).
Definition at line 242 of file i2c.c.
{
#endif
  // dummy
  // check different I2C status bits and react accordingly
  return;
} // i2c_ISR
uint8_t i2c_request (uint8_t slaveAddr, uint8_t numRx, uint8_t * bufRx)
request data via I2C as master
Parameters
[in] slaveAddr 7b address [6:0] of I2C slave
[in] numRx number of bytes to receive
[out] bufRx receive buffer
Returns
operation successful?
request data from I2C slave with a 5ms frame timeout. Note that no start or stop condition is generated.
Definition at line 194 of file i2c.c.
References check_timeout, ERROR_TIMOUT, start_timeout_ms(), stop_timeout_ms(), and SUCCESS.
{
  uint8_t      i;
  // init receive buffer
  for (i=0; i<numRx; i++)
    bufRx[i] = 0;
  // start overall timeout
  start_timeout_ms(5);
  // send 7b slave adress [7:1] + read flag (LSB=1)
  I2C.DR.byte = (uint8_t) ((slaveAddr << 1) | 0x01);        // shift left and set LSB (write=0, read=1)
  while ((!I2C.SR1.reg.ADDR) && (!check_timeout()));     // wait until adress sent or timeout
  while ((!I2C.SR3.reg.BUSY) && (!check_timeout()));     // seems to be required...???
  // receive data from slave
  for (i=0; i<numRx; i++) {
    while ((!I2C.SR1.reg.RXNE) && (!check_timeout()));   // wait until DR buffer not empty or timeout
    bufRx[i] = I2C.DR.byte;
  }
  // on I2C timeout set error flag
  if (check_timeout()) {
    stop_timeout_ms();
    return(ERROR_TIMOUT);
  }
  // reset timeout timer
  stop_timeout_ms();
  return(SUCCESS);
} // i2c_request
uint8_t i2c_send (uint8_t addr, uint8_t numTx, uint8_t * bufTx)
write data via I2C
Parameters
[in] addr 7b address [6:0] of I2C slave
[in] numTx number of bytes to send
[in] bufTx send buffer
Returns
operation successful?
write data via I2C with 5ms frame timeout. Note that no start or stop condition is generated.
Definition at line 143 of file i2c.c.
References check_timeout, ERROR_TIMOUT, start_timeout_ms(), stop_timeout_ms(), and SUCCESS.
Referenced by lcd_init(), lcd_print(), and set_dig_poti().
{
  uint8_t    i;
  // start overall timeout
  start_timeout_ms(5);
  // send 7b slave adress [7:1] + write flag (LSB=0)
  I2C.DR.byte = (uint8_t) ((addr << 1) & ~0x01);                 // shift left and set LSB (write=0, read=1)
  while ((!I2C.SR1.reg.ADDR) && (!check_timeout()));     // wait until address sent or timeout
  while ((!I2C.SR3.reg.BUSY) && (!check_timeout()));     // seems to be required...???
  // send data
  if (!check_timeout()) {
    for (i=0; i<numTx; i++) {
      I2C.DR.byte = bufTx[i];
      while ((!I2C.SR1.reg.TXE) && (!check_timeout()));    // wait until DR buffer empty or timeout
    }
  }
  // on I2C timeout set error flag
  if (check_timeout()) {
    stop_timeout_ms();
    return(ERROR_TIMOUT);
  }
  // reset timeout timer
  stop_timeout_ms();
  return(SUCCESS);
} // i2c_send
uint8_t i2c_start (void)
generate I2C start condition
Returns
error code
generate I2C start condition with 1ms timeout
Definition at line 70 of file i2c.c.
References check_timeout, ERROR_TIMOUT, start_timeout_ms(), stop_timeout_ms(), and SUCCESS.
Referenced by lcd_init(), lcd_print(), and set_dig_poti().
                    {
  // start overall timeout
  start_timeout_ms(1);
  // generate start condition
  I2C.CR2.reg.START = 1;
  while ((!I2C.SR1.reg.SB) && (!check_timeout()));       // wait for start condition generated or timeout
  // on I2C timeout set error flag
  if (check_timeout()) {
    stop_timeout_ms();
    return(ERROR_TIMOUT);
  }
  // reset timeout timer
  stop_timeout_ms();
  return(SUCCESS);
} // i2c_start
uint8_t i2c_stop (void)
generate I2C stop condition
Returns
operation successful?
generate I2C stop condition with 1ms timeout
Definition at line 104 of file i2c.c.
References check_timeout, ERROR_TIMOUT, start_timeout_ms(), stop_timeout_ms(), and SUCCESS.
Referenced by lcd_init(), lcd_print(), and set_dig_poti().
                   {
  // start overall timeout
  start_timeout_ms(1);
  // generate stop condition
  I2C.CR2.reg.STOP = 1;
  while ((I2C.SR3.reg.MSL) && (!check_timeout()));       // wait for stop condition generated or timeout
  // on I2C timeout set error flag
  if (check_timeout()) {
    stop_timeout_ms();
    return(ERROR_TIMOUT);
  }
  // reset timeout timer
  stop_timeout_ms();
  return(SUCCESS);
} // i2c_stop