STM8_Lib: uart1.h File Reference
uart1.h File Reference
declaration of UART1 functions & macros
#include <stdint.h>
#include "stm8as.h"
Functions
void uart1_init (uint32_t BR)
init UART1 for communication
void uart1_send (uint8_t data)
send byte via UART1
uint8_t uart1_check_Rx (void)
UART1 check if data was received.
uint8_t uart1_receive (void)
UART1 data receive function (if FIFO is used, remove data from it)
Detailed Description
declaration of UART1 functions & macros
Author
G. Icking-Konert
Date
2013-11-22
Version
0.1
declaration of UART1 functions and macros. Optional functionality via #define:
UART1_HALF_DUPLEX: communication via 1-wire interface, e.g. LIN -> ignore echo after send (default: 2-wire)
UART1_FIFO: send/receive is in background via interrupts and SW FIFO (default: blocking w/o FIFO)
Definition in file uart1.h.
Function Documentation
uint8_t uart1_check_Rx (void)
UART1 check if data was received.
UART1 check if data was received.
Returns
1 = data in FIFO resp. in UART1 buffer
check if data was received via UART1.
For direct UART1 access:
check if UART1 Rx data register contains data
If FIFO is used:
check if FIFO contains data
Definition at line 200 of file uart1.c.
References FIFO_NOT_EMPTY.
{
  uint8_t   result;
  // check Rx FIFO status
  #ifdef UART1_FIFO
    // check if FIFO contains data
    result = FIFO_NOT_EMPTY(m_UART1_Rx_Fifo);
  // check UART1 register
  #else // UART1_FIFO
    // check if UART1 Rx register contains data
    result = UART1.SR.reg.RXNE;
  #endif // UART1_FIFO
  // return FIFO status
  return(result);
} // uart1_check_Rx
void uart1_init (uint32_t BR)
init UART1 for communication
init UART1 for communication
Parameters
[in] BR baudrate [Baud]
initialize UART1 for communication with specified baudrate. Use 1 start, 8 data and 1 stop bit; no parity or flow control
If FIFO is used, initialize Rx and Tx FIFOs and activate Rx interrupt.
Definition at line 80 of file uart1.c.
References fifo_init().
{
  volatile uint16_t  val16;
  // init UART1 Rx pin (=PA4)
  PORT_A.DDR.bit.b4 = 0;  // input(=0) or output(=1)
  PORT_A.CR1.bit.b4 = 1;  // input: 0=float, 1=pull-up; output: 0=open-drain, 1=push-pull
  PORT_A.CR2.bit.b4 = 0;  // input: 0=no exint, 1=exint; output: 0=2MHz slope, 1=10MHz slope
  // init UART1 Tx pin (=PA5)
  PORT_A.ODR.bit.b5 = 1;  // init output to high
  PORT_A.DDR.bit.b5 = 1;  // input(=0) or output(=1)
  PORT_A.CR1.bit.b5 = 1;  // input: 0=float, 1=pull-up; output: 0=open-drain, 1=push-pull
  PORT_A.CR2.bit.b5 = 1;  // input: 0=no exint, 1=exint; output: 0=2MHz slope, 1=10MHz slope
  // set UART1 behaviour
  UART1.CR1.byte = 0x00;  // enable UART1, 8 data bits, no parity control
  UART1.CR2.byte = 0x00;  // no interrupts, disable sender/receiver
  UART1.CR3.byte = 0x00;  // no LIN support, 1 stop bit, no clock output(?)
  // set baudrate (note: BRR2 must be written before BRR1!)
  val16 = (uint16_t) (((uint32_t) 16000000L)/BR);
  UART1.BRR2.byte = (uint8_t) (((val16 & 0xF000) >> 8) | (val16 & 0x000F));
  UART1.BRR1.byte = (uint8_t) ((val16 & 0x0FF0) >> 4);
  // enable transmission
  UART1.CR2.reg.REN = 1; // enable receiver
  UART1.CR2.reg.TEN = 1; // enable sender
  #ifdef UART1_FIFO
    // init FIFOs for receive and transmit
    fifo_init(&m_UART1_Rx_Fifo);
    fifo_init(&m_UART1_Tx_Fifo);
    // enable Rx interrupt. Tx interrupt is enabled in uart1_send()
    UART1.CR2.reg.RIEN = 1;
  #endif // UART1_FIFO
} // uart1_init
uint8_t uart1_receive (void)
UART1 data receive function (if FIFO is used, remove data from it)
UART1 data receive function (if FIFO is used, remove data from it)
Returns
oldest, not treated data
For direct UART1 access:
return content of UART1 Rx data register
If FIFO is used:
checks if data exists in the Rx FIFO software buffer
if data exists, return oldest FIFO element
remove oldest FIFO element from FIFO
Definition at line 241 of file uart1.c.
References fifo_dequeue(), and SW_RESET.
{
  uint8_t   data;
  // get Rx data from FIFO
  #ifdef UART1_FIFO
    // disable UART1 "Rx full interrupt" while manipulating Rx FIFO
    UART1.CR2.reg.RIEN = 0;
    // get oldest FIFO element (or -128 if FIFO is empty)
    data = fifo_dequeue(&m_UART1_Rx_Fifo);
    // re-enable UART1 "Rx full interrupt"
    UART1.CR2.reg.RIEN = 1;
  // get data from UART1 register
  #else // UART1_FIFO
    // get content of UART1 Rx register
    data = UART1.DR.byte;
    // optional check for UART reset command
    #ifdef UART1_RST
      // check next byte vs. keyword
      if (data == m_UART1_cmdReset[m_UART1_idxReset])
        m_UART1_idxReset++;
      else
        m_UART1_idxReset = 0;
      // trigger SW reset if full keyword received
      if (m_UART1_idxReset >= m_UART1_lenReset)
        SW_RESET;
    #endif // UART1_RST
  #endif // UART1_FIFO
  // return the FIFO data
  return(data);
} // uart1_receive
void uart1_send (uint8_t data)
send byte via UART1
Parameters
[in] byte data to send
send byte via UART1.
For direct UART1 access:
send byte via UART1 directly
If FIFO is used:
stores data into the Tx FIFO software buffer
enable the UART1 "Tx buffer empty" interrupt
actual transmission is handled by TXE interrupt routine
Definition at line 141 of file uart1.c.
References fifo_enqueue(), and FIFO_FULL.
Referenced by putchar().
{
  // send data in background using FIFO
  #ifdef UART1_FIFO
    // wait until FIFO has free space
    while(FIFO_FULL(m_UART1_Tx_Fifo));
    // disable UART1 "Tx empty interrupt" while manipulating Tx FIFO
    UART1.CR2.reg.TIEN = 0;
    // store byte in software FIFO
    fifo_enqueue(&m_UART1_Tx_Fifo, data);
    // enable UART1 "Tx empty interrupt" to handle sending data
    UART1.CR2.reg.TIEN = 1;
  // send data blocking without FIFO
  #else // UART1_FIFO
    // wait until TX buffer is available
    while (!(UART1.SR.reg.TXE));
    // for 1-wire I/F (e.g. LIN) disable receiver
    #ifdef UART1_HALF_DUPLEX
      UART1.CR2.reg.REN = 0;
    #endif // UART1_HALF_DUPLEX
    // send byte
    UART1.DR.byte = data;
    // for 1-wire I/F (e.g. LIN) wait until byte is sent, then re-enable receiver
    #ifdef UART1_HALF_DUPLEX
      while (!(UART1.SR.reg.TXE));
      UART1.CR2.reg.REN = 1;
    #endif // UART1_HALF_DUPLEX
  #endif // UART1_FIFO
} // uart1_send