STM8_Lib: i2c_lcd.c File Reference
i2c_lcd.c File Reference
implementation of 2x16 LCD output functions/macros
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include "stm8as.h"
#include "gpio.h"
#include "timer3.h"
#include "i2c.h"
#include "i2c_lcd.h"
#include "error_codes.h"
Functions
uint8_t lcd_init ()
initialize LCD for output
void lcd_clear ()
clear LCD
void lcd_print (uint8_t line, uint8_t col, char *s)
print to LCD display
Detailed Description
implementation of 2x16 LCD output functions/macros
Author
G. Icking-Konert
Date
2013-11-22
Version
0.1
implementation of functions for printing strings via I2C to 2x16 LCD Batron BTHQ21605V-COG-FSRE-I2C (Farnell 1220409). Connect LCD I2C bus to STM8 SCL/SDA, and LCD reset pin to STM8 pin PE3
Definition in file i2c_lcd.c.
Function Documentation
void lcd_clear (void)
clear LCD
Definition at line 93 of file i2c_lcd.c.
References lcd_print().
Referenced by lcd_init().
                 {
  uint8_t   str[1];
  // print empty lines to both lines clears LCD
  sprintf(str, "");
  lcd_print(1, 1, str);
  lcd_print(2, 1, str);
} // lcd_clear
uint8_t lcd_init (void)
initialize LCD for output
initialize I2C, and reset LCD
Returns
is an LCD attached?
initialize LCD for LCD output. Also check if LCD display is attached via bus timeout
Definition at line 45 of file i2c_lcd.c.
References GPIO_HIGH, gpio_init(), GPIO_LOW, i2c_send(), i2c_start(), i2c_stop(), LCD_ADDR_I2C, lcd_clear(), OUTPUT_PUSHPULL_SLOW, PIN_3, sleep_ms(), and SUCCESS.
                   {
  uint8_t   status;
  // configure PE3 as reset pin (active high)
  gpio_init(&PORT_E, PIN_3, OUTPUT_PUSHPULL_SLOW);
  // reset LCD display
  sleep_ms(10);
  GPIO_HIGH(PORT_E, PIN_3);
  sleep_ms(10);
  GPIO_LOW(PORT_E, PIN_3);
  sleep_ms(10);
  // check if LCD present by sending a dummy frame
  // generate start condition
  i2c_start();
  // send dummy frame (with timeout)
  status = (uint8_t) (i2c_send(LCD_ADDR_I2C, 0, NULL));
  // generate stop condition
  i2c_stop();
  // if LCD is present clear it
  if (status == SUCCESS)
    lcd_clear();
  // return LCD status
  return(status);
} // lcd_init
void lcd_print (uint8_t line, uint8_t col, char * s)
print to LCD display
print string to LCD diplay
Parameters
line line to print to (1 or 2)
col column to start at
s string to print
print up to 16 chars to line in LCD display
Definition at line 118 of file i2c_lcd.c.
References check_timeout, I2C_BUSY, i2c_send(), i2c_start(), i2c_stop(), LCD_ADDR_I2C, start_timeout_ms(), and stop_timeout_ms().
Referenced by lcd_clear().
{
  uint8_t   s2[21];
  uint8_t   len;
  uint8_t   i, j;
  // config display
  i = 0;
  s2[i++] = 0x00;                   // control byte 'config mode'
  s2[i++] = 0x34;                   // command 'function set'
  s2[i++] = 0x0C;                   // command 'display on'
  s2[i++] = 0x06;                   // command 'entry mode'
  if (line == 1)
    s2[i++] = (uint8_t)(0x80 + col - 1); // DRAM adress offset for line 1 + column
  else
    s2[i++] = (uint8_t)(0xC0 + col - 1); // DRAM adress offset for line 2
  // wait until bus is free (with timeout)
  start_timeout_ms(100);
  while ((I2C_BUSY) && (!check_timeout()));
  // generate start condition
  i2c_start();
  // send data (with timeout)
  i2c_send(LCD_ADDR_I2C, i, s2);
  // send string
  // init array to SPC
  for (i=0; i<20; i++)
    s2[i] = 0xA0;
  i = 0;
  s2[i++] = 0x40;     // control byte 'write data'
  // copy string
  len = (uint8_t) strlen(s);
  for (j=0; (j<len) && (j<21); j++) {
    // replace TAB, CR, LF, BEL with SPC
    if ((s[j] == '\t') || (s[j] == '\r') || (s[j] == '\n') || (s[j] == 7))
      s2[i++] = 0xA0;
    // convert ASCII to lcd char set (+128)
    else
      s2[i++] = (uint8_t)(s[j] | 0x80);
  }
  // generate start condition again to witch to "write data" mode
  i2c_start();
  // send to LCD (with timeout)
  i2c_send(LCD_ADDR_I2C, 17, s2);
  // generate stop condition
  i2c_stop();
  // wait until bus is free (with timeout)
  start_timeout_ms(100);
  while ((I2C_BUSY) && (!check_timeout()));
  // on I2C timeout set error flag
  if (check_timeout()) {
    stop_timeout_ms();
    return;
  }
  // reset timeout timer
  stop_timeout_ms();
} // lcd_print