STM8_Lib: uart3.c File Reference
uart3.c File Reference
implementation of UART3 functions/macros
#include <stdio.h>
#include <stdint.h>
#include "stm8as.h"
#include "uart3.h"
Functions
void uart3_init (uint32_t BR)
initialize UART3 for communication
void uart3_send (uint8_t data)
send byte via UART3
uint8_t uart3_check_Rx (void)
check if data was received via UART3
uint8_t uart3_receive (void)
UART3 data receive function.
Detailed Description
implementation of UART3 functions/macros
Author
G. Icking-Konert
Date
2013-11-22
Version
0.1
implementation of UART3 functions and macros. Optional functionality via #define:
UART3_HALF_DUPLEX: communication via 1-wire interface, e.g. LIN -> ignore echo after send (default: 2-wire)
UART3_FIFO: send/receive is in background via interrupts and SW FIFO (default: blocking w/o FIFO)
UART3_RST: trigger SW reset on reception of "Re5eT!"
Definition in file uart3.c.
Function Documentation
uint8_t uart3_check_Rx (void)
check if data was received via UART3
UART3 check if data was received.
Returns
1 = data in FIFO resp. in UART3 buffer
check if data was received via UART3.
For direct UART3 access:
check if UART3 Rx data register contains data
If FIFO is used:
check if FIFO contains data
Definition at line 200 of file uart3.c.
References FIFO_NOT_EMPTY.
{
  uint8_t   result;
  // check Rx FIFO status
  #ifdef UART3_FIFO
    // check if FIFO contains data
    result = FIFO_NOT_EMPTY(m_UART3_Rx_Fifo);
  // check UART3 register
  #else // UART3_FIFO
    // check if UART3 Rx register contains data
    result = UART3.SR.reg.RXNE;
  #endif // UART3_FIFO
  // return FIFO status
  return(result);
} // uart3_check_Rx
void uart3_init (uint32_t BR)
initialize UART3 for communication
init UART3 for communication
Parameters
[in] BR baudrate [Baud]
initialize UART3 for communication with specified baudrate. Use 1 start, 8 data and 1 stop bit; no parity or flow control
If FIFO is used, initialize Rx and Tx FIFOs and activate Rx interrupt.
Definition at line 80 of file uart3.c.
References fifo_init().
{
  volatile uint16_t  val16;
  // init UART3 Rx pin (=PA4)
  PA.DDR.bit.b4 = 0;  // input(=0) or output(=1)
  PA.CR1.bit.b4 = 1;  // input: 0=float, 1=pull-up; output: 0=open-drain, 1=push-pull
  PA.CR2.bit.b4 = 0;  // input: 0=no exint, 1=exint; output: 0=2MHz slope, 1=10MHz slope
  // init UART3 Tx pin (=PA5)
  PA.ODR.bit.b5 = 1;  // init output to high
  PA.DDR.bit.b5 = 1;  // input(=0) or output(=1)
  PA.CR1.bit.b5 = 1;  // input: 0=float, 1=pull-up; output: 0=open-drain, 1=push-pull
  PA.CR2.bit.b5 = 1;  // input: 0=no exint, 1=exint; output: 0=2MHz slope, 1=10MHz slope
  // set UART3 behaviour
  UART3.CR1.byte = 0x00;  // enable UART3, 8 data bits, no parity control
  UART3.CR2.byte = 0x00;  // no interrupts, disable sender/receiver
  UART3.CR3.byte = 0x00;  // no LIN support, 1 stop bit, no clock output(?)
  // set baudrate (note: BRR2 must be written before BRR1!)
  val16 = (uint16_t) (((uint32_t) 16000000L)/BR);
  UART3.BRR2.byte = (uint8_t) (((val16 & 0xF000) >> 8) | (val16 & 0x000F));
  UART3.BRR1.byte = (uint8_t) ((val16 & 0x0FF0) >> 4);
  // enable transmission
  UART3.CR2.reg.REN = 1; // enable receiver
  UART3.CR2.reg.TEN = 1; // enable sender
  #ifdef UART3_FIFO
    // init FIFOs for receive and transmit
    fifo_init(&m_UART3_Rx_Fifo);
    fifo_init(&m_UART3_Tx_Fifo);
    // enable Rx interrupt. Tx interrupt is enabled in uart3_send()
    UART3.CR2.reg.RIEN = 1;
  #endif // UART3_FIFO
} // uart3_init
uint8_t uart3_receive (void)
UART3 data receive function.
UART3 data receive function (if FIFO is used, remove data from it)
Returns
oldest, not treated data
For direct UART3 access:
return content of UART3 Rx data register
If FIFO is used:
checks if data exists in the Rx FIFO software buffer
if data exists, return oldest FIFO element
remove oldest FIFO element from FIFO
Definition at line 241 of file uart3.c.
References fifo_dequeue(), and SW_RESET.
{
  uint8_t   data;
  // get Rx data from FIFO
  #ifdef UART3_FIFO
    // disable UART3 "Rx full interrupt" while manipulating Rx FIFO
    UART3.CR2.reg.RIEN = 0;
    // get oldest FIFO element (or -128 if FIFO is empty)
    data = fifo_dequeue(&m_UART3_Rx_Fifo);
    // re-enable UART3 "Rx full interrupt"
    UART3.CR2.reg.RIEN = 1;
  // get data from UART3 register
  #else // UART3_FIFO
    // get content of UART3 Rx register
    data = UART3.DR.byte;
    // optional check for UART reset command
    #ifdef UART3_RST
      // check next byte vs. keyword
      if (data == m_UART3_cmdReset[m_UART3_idxReset])
        m_UART3_idxReset++;
      else
        m_UART3_idxReset = 0;
      // trigger SW reset if full keyword received
      if (m_UART3_idxReset >= m_UART3_lenReset)
        SW_RESET;
    #endif // UART3_RST
  #endif // UART3_FIFO
  // return the FIFO data
  return(data);
} // uart3_receive
void uart3_send (uint8_t data)
send byte via UART3
Parameters
[in] byte data to send
send byte via UART3.
For direct UART3 access:
send byte via UART3 directly
If FIFO is used:
stores data into the Tx FIFO software buffer
enable the UART3 "Tx buffer empty" interrupt
actual transmission is handled by TXE interrupt routine
Definition at line 141 of file uart3.c.
References fifo_enqueue(), and FIFO_FULL.
{
  // send data in background using FIFO
  #ifdef UART3_FIFO
    // wait until FIFO has free space
    while(FIFO_FULL(m_UART3_Tx_Fifo));
    // disable UART3 "Tx empty interrupt" while manipulating Tx FIFO
    UART3.CR2.reg.TIEN = 0;
    // store byte in software FIFO
    fifo_enqueue(&m_UART3_Tx_Fifo, data);
    // enable UART3 "Tx empty interrupt" to handle sending data
    UART3.CR2.reg.TIEN = 1;
  // send data blocking without FIFO
  #else // UART3_FIFO
    // wait until TX buffer is available
    while (!(UART3.SR.reg.TXE));
    // for 1-wire I/F (e.g. LIN) disable receiver
    #ifdef UART3_HALF_DUPLEX
      UART3.CR2.reg.REN = 0;
    #endif // UART3_HALF_DUPLEX
    // send byte
    UART3.DR.byte = data;
    // for 1-wire I/F (e.g. LIN) wait until byte is sent, then re-enable receiver
    #ifdef UART3_HALF_DUPLEX
      while (!(UART3.SR.reg.TXE));
      UART3.CR2.reg.REN = 1;
    #endif // UART3_HALF_DUPLEX
  #endif // UART3_FIFO
} // uart3_send