STM8_Lib: sw_fifo.h File Reference
sw_fifo.h File Reference
declaration and implementation of inline functions and macros for a SW FIFO
#include <stdint.h>
Data Structures
struct fifo_t
data structure of the SW FIFO buffer. To safe RAM, encode flags in 1B and use size dependent pointer type
Macros
#define FIFO_BUFFER_SIZE 32
#define FIFO_OPTIMIZE_RAM 1
#define FIFO_NOT_EMPTY(a) (a.flags & 0x01)
#define FIFO_FULL(a) (a.flags & 0x02)
#define FIFO_OVERFLOW(a) (a.flags & 0x04)
#define FIFO_SET_NOT_EMPTY(a) (a->flags |= 0x01)
#define FIFO_SET_FULL(a) (a->flags |= 0x02)
#define FIFO_SET_OVERFLOW(a) (a->flags |= 0x04)
#define FIFO_CLEAR_NOT_EMPTY(a) (a->flags &= ~0x01)
#define FIFO_CLEAR_FULL(a) (a->flags &= ~0x02)
#define FIFO_CLEAR_OVERFLOW(a) (a->flags &= ~0x04)
Functions
void fifo_init (fifo_t *buf)
init FIFO data structure
void fifo_enqueue (fifo_t *buf, uint8_t data)
add a new byte to the FIFO buffer
uint8_t fifo_dequeue (fifo_t *buf)
get oldest byte from the FIFO buffer
uint8_t fifo_peek (fifo_t *buf)
peek oldest byte in FIFO buffer without removing it
void fifo_print (fifo_t *buf)
for debugging print FIFO content to stdio (requires putchar()!)
Detailed Description
declaration and implementation of inline functions and macros for a SW FIFO
Author
G. Icking-Konert
Date
2015-04-06
Version
0.1
declares and implementats a generic SW FIFO buffer, e.g. for sending and receiving via UART. Most action is done insede of interrupt service routines. For speed functions are declared as inline. This FIFO is a generalized version of code by Scott Schmit available at https://eewiki.net/display/microcontroller/Software+FIFO+Buffer+for+UART+Communication
Note
FIFO buffer size is configured via FIFO_BUFFER_SIZE (default=32)
for different size re-define FIFO_BUFFER_SIZE in the calling C-file
several FIFOs within the calling C-file have the same buffer size FIFO_BUFFER_SIZE
FIFO buffers in different C-files can have different sizes set via FIFO_BUFFER_SIZE
status handling can be optimized for RAM size or flash size & speed via FIFO_OPTIMIZE_RAM (default=1)
for a different setting re-define FIFO_OPTIMIZE_RAM in the calling C-file
FIFO_OPTIMIZE_RAM=1 –> status bits are stored in 1 byte –> save 2B RAM/FIFO
FIFO_OPTIMIZE_RAM=0 –> each status flag is stored in 1 byte –> save ~25B flash/FIFO and gain some speed
Definition in file sw_fifo.h.
Macro Definition Documentation
#define FIFO_BUFFER_SIZE 32
Definition at line 44 of file sw_fifo.h.
Referenced by fifo_dequeue(), and fifo_enqueue().
#define FIFO_CLEAR_FULL (a) (a->flags &= ~0x02)
Definition at line 65 of file sw_fifo.h.
Referenced by fifo_dequeue(), and fifo_init().
#define FIFO_CLEAR_NOT_EMPTY (a) (a->flags &= ~0x01)
Definition at line 64 of file sw_fifo.h.
Referenced by fifo_dequeue(), fifo_init(), and fifo_peek().
#define FIFO_CLEAR_OVERFLOW (a) (a->flags &= ~0x04)
Definition at line 66 of file sw_fifo.h.
Referenced by fifo_init().
#define FIFO_FULL (a) (a.flags & 0x02)
Definition at line 55 of file sw_fifo.h.
Referenced by uart1_send(), and uart3_send().
#define FIFO_NOT_EMPTY (a) (a.flags & 0x01)
Definition at line 54 of file sw_fifo.h.
Referenced by fifo_print(), uart1_check_Rx(), and uart3_check_Rx().
#define FIFO_OPTIMIZE_RAM 1
Definition at line 49 of file sw_fifo.h.
#define FIFO_OVERFLOW (a) (a.flags & 0x04)
Definition at line 56 of file sw_fifo.h.
#define FIFO_SET_FULL (a) (a->flags |= 0x02)
Definition at line 60 of file sw_fifo.h.
Referenced by fifo_enqueue().
#define FIFO_SET_NOT_EMPTY (a) (a->flags |= 0x01)
Definition at line 59 of file sw_fifo.h.
Referenced by fifo_enqueue().
#define FIFO_SET_OVERFLOW (a) (a->flags |= 0x04)
Definition at line 61 of file sw_fifo.h.
Referenced by fifo_enqueue().
Function Documentation
uint8_t fifo_dequeue (fifo_t * buf) inline
get oldest byte from the FIFO buffer
Parameters
[in] buf pointer to FIFO structure
Returns
oldest byte from the FIFO buffer. If empty, return 255
get oldest byte from the FIFO buffer. Actions:
if data in buffer, return the oldest element and remove it from buffer
if buffer empty, clear the "FIFO not empty" bit
clear "FIFO full" warning bit (no longer true)
do not change "FIFO overflow" bit to keep track of errors. Needs to be cleared by SW
Note
to ensure data consistency, disable connected interrupts if called from outside interrupt service routine
Definition at line 222 of file sw_fifo.h.
References fifo_t::buffer, FIFO_BUFFER_SIZE, FIFO_CLEAR_FULL, FIFO_CLEAR_NOT_EMPTY, fifo_t::idxFirst, and fifo_t::numBytes.
Referenced by fifo_print(), uart1_receive(), and uart3_receive().
{
#endif
  uint8_t data = 255;     // =FIFO empty
  // if FIFO is empty clear the "FIFO not empty" bit and return immediately
  if(buf->numBytes == 0) {
    FIFO_CLEAR_NOT_EMPTY(buf);
    return(data);
  }
  // grab the oldest element in the buffer
  data = buf->buffer[buf->idxFirst];
  // increment index of oldest element. Clip to buffer size
  if ((++(buf->idxFirst)) >= FIFO_BUFFER_SIZE)
    buf->idxFirst = 0;
  // decrement the bytes counter. If FIFO is empty, clear "not empty" bit
  if ((--(buf->numBytes)) == 0)
    FIFO_CLEAR_NOT_EMPTY(buf);
  // clear full bit, since we just made space
  FIFO_CLEAR_FULL(buf);
  // do not clear overflow bit to keep track of error. Needs to be cleared by SW
  // return the read byte
  return(data);
} // fifo_dequeue
void fifo_enqueue (fifo_t * buf, uint8_t data) inline
add a new byte to the FIFO buffer
Parameters
[in] buf pointer to FIFO structure
[in] data byte to add to SW FIFO buffer
add a new byte to the SW FIFO buffer. Actions:
if space available in buffer, add data to it
set "not empty" bit
if buffer is full afterwards, add data and set "full" warning bit
on buffer overflows discard new data and set "overflow" error bit
Note
to ensure data consistency, disable connected interrupts if called from outside interrupt service routine
Definition at line 172 of file sw_fifo.h.
References fifo_t::buffer, FIFO_BUFFER_SIZE, FIFO_SET_FULL, FIFO_SET_NOT_EMPTY, FIFO_SET_OVERFLOW, fifo_t::idxLast, and fifo_t::numBytes.
Referenced by uart1_send(), and uart3_send().
{
#endif
  // if the FIFO buffer is full set overflow bit and return immediately
  if(buf->numBytes >= FIFO_BUFFER_SIZE) {
    FIFO_SET_OVERFLOW(buf);
    return;
  }
  // store data as newest element in the buffer
  buf->buffer[buf->idxLast] = data;
  // increment index of newest element. Clip to buffer size
  if ((++(buf->idxLast)) >= FIFO_BUFFER_SIZE)
    buf->idxLast = 0;
  // increment the bytes counter. If FIFO is full, set warning bit
  if ((++(buf->numBytes)) == FIFO_BUFFER_SIZE)
    FIFO_SET_FULL(buf);
  // set "FIFO not empty" bit
  FIFO_SET_NOT_EMPTY(buf);
} // fifo_enqueue
void fifo_init (fifo_t * buf) inline
init FIFO data structure
Parameters
[in] buf pointer to FIFO structure
init FIFO data structure. Actions:
reset FIFO index pointers
reset status bits
Note
to ensure data consistency, disable connected interrupts if called from outside interrupt service routine
Definition at line 136 of file sw_fifo.h.
References FIFO_CLEAR_FULL, FIFO_CLEAR_NOT_EMPTY, FIFO_CLEAR_OVERFLOW, fifo_t::idxFirst, fifo_t::idxLast, and fifo_t::numBytes.
Referenced by uart1_init(), and uart3_init().
{
#endif
  // reset FIFO data
  FIFO_CLEAR_NOT_EMPTY(buf);  // set "FIFO empty" status
  FIFO_CLEAR_FULL(buf);       // reset "FIFO full" status
  FIFO_CLEAR_OVERFLOW(buf);   // set "FIFO overflow" status
  buf->idxFirst = 0;          // index of oldest byte in buffer
  buf->idxLast  = 0;          // index of newest byte in buffer
  buf->numBytes = 0;          // number of bytes in buffer
} // fifo_init
uint8_t fifo_peek (fifo_t * buf) inline
peek oldest byte in FIFO buffer without removing it
Parameters
[in] buf pointer to FIFO structure
Returns
oldest byte from the FIFO buffer. If empty, return 255
peek oldest byte in FIFO buffer without removing it. Actions:
if data in buffer, return the oldest element but keep it in buffer
if buffer empty, clear the "FIFO not empty" bit
Note
to ensure data consistency, disable connected interrupts if called from outside interrupt service routine
Definition at line 277 of file sw_fifo.h.
References fifo_t::buffer, FIFO_CLEAR_NOT_EMPTY, fifo_t::idxFirst, and fifo_t::numBytes.
{
#endif
  uint8_t data = 255;   // =FIFO empty
  // if FIFO is empty clear the "FIFO not empty" bit and return immediately
  if(buf->numBytes == 0) {
    FIFO_CLEAR_NOT_EMPTY(buf);
    return(data);
  }
  // grab the oldest element in the buffer
  data = buf->buffer[buf->idxFirst];
  // return the read byte
  return(data);
} // fifo_peek
void fifo_print (fifo_t * buf) inline
for debugging print FIFO content to stdio (requires putchar()!)
Parameters
[in] buf pointer to FIFO structure
print FIFO content for debugging using printf(). This needs putchar() to be implemented.
Note
to ensure data consistency, disable connected interrupts if called from outside interrupt service routine
Definition at line 315 of file sw_fifo.h.
References fifo_dequeue(), FIFO_NOT_EMPTY, fifo_t::flags, fifo_t::idxFirst, fifo_t::idxLast, and fifo_t::numBytes.
{
#endif
  uint8_t   c;
  printf("num=%d;  ", (int) buf->numBytes);
  printf("first=%d; last=%d;  ", (int) buf->idxFirst, (int) buf->idxLast);
#if FIFO_OPTIMIZE_RAM
  printf("flags: 0x%02x;  ", (int) buf->flags);
#else
  printf("empty=%d full=%d overflow=%d;  ", (int) buf->fifo_not_empty, (int) buf->fifo_full, (int) buf->fifo_overflow);
#endif // FIFO_OPTIMIZE_RAM
  printf("data=");
  while (FIFO_NOT_EMPTY((*buf))) {
    c = fifo_dequeue(buf);
    printf("%d ", (int) c);
  }
} // fifo_print