STM8_Lib: timer3.c File Reference
timer3.c File Reference
implementation of timer TIM3 functions/macros for sleep_x and timeout
#include <stdint.h>
#include "stm8as.h"
#include "timer3.h"
Functions
void tim3_init (void)
init timer 3 (sleep_x/timeout)
void sleep_ns (uint16_t dt)
halt code execution for specified 62.5ns units
void sleep_us (uint16_t dt)
halt code execution for specified microseconds
void sleep_ms (uint16_t dt)
halt code execution for specified milliseconds
void start_timeout_ms (uint16_t dt)
start timeout with specified number of ms
void stop_timeout_ms ()
top timeout timer
Detailed Description
implementation of timer TIM3 functions/macros for sleep_x and timeout
Author
G. Icking-Konert
Date
2013-11-22
Version
0.1
implementation of timer TIM3 functions for sleep_x and timeout via polling
Definition in file timer3.c.
Function Documentation
void sleep_ms (uint16_t dt)
halt code execution for specified milliseconds
halt code execution for dt milliseconds
Parameters
dt halt duration in ms
code execution is halted for specified number of milliseconds.
Definition at line 160 of file timer3.c.
Referenced by beep(), and lcd_init().
{
  // stop timer
  TIM3.CR1.reg.CEN = 0;
  // set prescaler to fclk/2^14 -> ~1kHz clock
  TIM3.PSCR.reg.PSC = 14;
  // set timout to dt ms (freq_Hz=fclk/(prescaler*ARR)) (write high byte first)
  TIM3.CC1R.byteH = (uint8_t) (dt >> 8);
  TIM3.CC1R.byteL = (uint8_t) dt;
  // reset counter register (write high byte first)
  TIM3.CNTR.byteH = (uint8_t) 0;
  TIM3.CNTR.byteL = (uint8_t) 0;
  // clear status registers
  TIM3.SR1.byte = 0x00;
  // request register update
  TIM3.EGR.reg.UG = 1;
  // start the timer
  TIM3.CR1.reg.CEN = 1;
  // wait for overflow (no interrupts!)
  while (!TIM3.SR1.reg.CC1IF);
} // sleep_ms
void sleep_ns (uint16_t dt)
halt code execution for specified 62.5ns units
halt code execution for dt*62.5ns
Parameters
dt halt duration in 62.5ns units
code execution is halted for specified number of 62.5ns units.
Definition at line 75 of file timer3.c.
{
  // convert 250ns-->62.5ns
  dt *= 4;
  // stop timer
  TIM3.CR1.reg.CEN = 0;
  // set prescaler to fclk -> 16MHz clock -> 62.5ns resolution
  TIM3.PSCR.reg.PSC = 0;
  // set timout to dt*250ns (freq_Hz=fclk/(prescaler*ARR)) (write high byte first)
  TIM3.CC1R.byteH = (uint8_t) (dt >> 8);
  TIM3.CC1R.byteL = (uint8_t) dt;
  // reset counter register (write high byte first)
  TIM3.CNTR.byteH = (uint8_t) 0;
  TIM3.CNTR.byteL = (uint8_t) 0;
  // request register update
  TIM3.EGR.reg.UG = 1;
  // clear status registers
  TIM3.SR1.byte = 0x00;
  // start the timer
  TIM3.CR1.reg.CEN = 1;
  // wait for overflow (no interrupts!)
  while (!TIM3.SR1.reg.CC1IF);
} // sleep_ns
void sleep_us (uint16_t dt)
halt code execution for specified microseconds
halt code execution for dt microseconds
Parameters
dt halt duration in us
code execution is halted for specified number of microseconds.
Definition at line 119 of file timer3.c.
Referenced by spi_send_receive().
{
  // stop timer
  TIM3.CR1.reg.CEN = 0;
  // set prescaler to fclk/2^4 -> 1MHz clock -> 1us resolution
  TIM3.PSCR.reg.PSC = 4;
  // set timout to dt us (freq_Hz=fclk/(prescaler*ARR)) (write high byte first)
  TIM3.CC1R.byteH = (uint8_t) (dt >> 8);
  TIM3.CC1R.byteL = (uint8_t) dt;
  // reset counter register (write high byte first)
  TIM3.CNTR.byteH = (uint8_t) 0;
  TIM3.CNTR.byteL = (uint8_t) 0;
  // request register update
  TIM3.EGR.reg.UG = 1;
  // clear status registers
  TIM3.SR1.byte = 0x00;
  // start the timer
  TIM3.CR1.reg.CEN = 1;
  // wait for overflow (no interrupts!)
  while (!TIM3.SR1.reg.CC1IF);
} // sleep_us
void start_timeout_ms (uint16_t dt)
start timeout with specified number of ms
start timeout timer
Parameters
dt timeout duration in ms (0=forever)
start timeout with specified number of milliseconds. To check for timeout query respective timer overflow flag.
Definition at line 202 of file timer3.c.
Referenced by i2c_request(), i2c_send(), i2c_start(), i2c_stop(), lcd_print(), set_dig_poti(), tim1_receive_SENT(), and tim2_receive_SENT().
{
  // stop timer
  TIM3.CR1.reg.CEN = 0;
  // prescaler to fclk/2^14 -> ~1kHz clock
  TIM3.PSCR.reg.PSC = 14;
  // set auto-reload value to n us (freq_Hz=fclk/(prescaler*ARR)) (write high byte first)
  TIM3.CC1R.byteH = (uint8_t) (dt >> 8);
  TIM3.CC1R.byteL = (uint8_t) dt;
  // reset counter register (write high byte first)
  TIM3.CNTR.byteH = 0;
  TIM3.CNTR.byteL = 0;
  // request register update
  TIM3.EGR.reg.UG = 1;
  // clear status registers
  TIM3.SR1.byte = 0x00;
  // reset timeout flag
  TIM3.SR1.reg.CC1IF = 0;
  // start the timer only if dt!=0
  if (dt != 0)
    TIM3.CR1.reg.CEN = 1;
  else
    TIM3.CR1.reg.CEN = 0;
} // start_timeout_ms
void stop_timeout_ms (void)
top timeout timer
start timeout timer
stop the timeout timer to avoid conflicts e.g. with sleep_x.
Definition at line 244 of file timer3.c.
Referenced by i2c_request(), i2c_send(), i2c_start(), i2c_stop(), lcd_print(), set_dig_poti(), tim1_receive_SENT(), and tim2_receive_SENT().
                       {
  // stop timer
  TIM3.CR1.reg.CEN = 0;
  // set prescaler to fclk/2^4 -> 1MHz clock -> 1us resolution
  TIM3.PSCR.reg.PSC = 4;
} // stop_timeout_ms
void tim3_init (void)
init timer 3 (sleep_x/timeout)
init timer 3 (sleep/timeout)
init timer TIM3 (used for sleep_x and timeout).
Definition at line 33 of file timer3.c.
                     {
  // stop the timer
  TIM3.CR1.reg.CEN = 0;
  // disable single-shot mode (causes SW stalls)
  TIM3.CR1.reg.OPM = 0;
  // set prescaler to fclk/2^4 -> 1MHz clock -> 1us resolution
  TIM3.PSCR.reg.PSC = 4;
  // init to 1ms timeout (write high byte first)
  TIM3.CC1R.byteH = 0x03;
  TIM3.CC1R.byteL = 0xE8;
  // clear status registers
  TIM3.SR1.byte = 0x00;
  TIM3.SR2.byte = 0x00;
  // reset counter register (write high byte first)
  TIM3.CNTR.byteH = 0;
  TIM3.CNTR.byteL = 0;
  // request register update
  TIM3.EGR.reg.UG = 1;
  // disable T3 interrupts
  TIM3.IER.byte = 0x00;
} // tim3_init